### ISSUE TITLE
Addon is not connecting to Amazon

### ISSUE THREAD

**Issue by ValleBL** [thiagobruch/HA_Addons#8]
First of all, thanks for you great work on that!
I'm currently setting this up to fulfill the ToDoist issue with Alexa.

For me it looks like the addon can not connect or redirect to amazon (according to Log)
```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
/app/node_modules/puppeteer-core/lib/cjs/puppeteer/util/Deferred.js:59
            this.#timeoutError = new Errors_js_1.TimeoutError(opts.message);
                                 ^

TimeoutError: Navigation timeout of 60000 ms exceeded
    at new Deferred (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/util/Deferred.js:59:34)
    at Deferred.create (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/util/Deferred.js:21:16)
    at new LifecycleWatcher (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/LifecycleWatcher.js:69:60)
    at CdpFrame.waitForNavigation (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Frame.js:199:29)
    at CdpFrame.<anonymous> (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/util/decorators.js:98:27)
    at CdpPage.waitForNavigation (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Page.js:619:43)
    at /app/scrapeAmazon.js:117:24

Node.js v21.7.3
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

I'm using OTP (not SMS) and German Amazon URL's (btw the Shopping List is accessible for me in the desktop browser)
```
Amazon_Login: user@mail.com
Amazon_Pass: password
Amazon_Secret: TokenWithoutSpaces
HA_Webhook_URL: >-
  http://IP:8123/api/webhook/import-alexa-shoppinglist-rx_TOKEN
Amazon_Sign_in_URL: >-
  https://www.amazon.de/ap/signin?openid.pape.max_auth_age=3600&openid.return_to=https%3A%2F%2Fwww.amazon.de%2Falexaquantum%2Fsp%2FalexaShoppingList%3Fref_%3Dlist_d_wl_ys_list_1&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.assoc_handle=amzn_alexa_quantum_de&openid.mode=checkid_setup&language=de_DE&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0
Amazon_Shopping_List_Page: >-
  https://www.amazon.de/alexaquantum/sp/alexaShoppingList?ref_=list_d_wl_ys_list_1
Delete_After_Download: true
```

Any hints on solving that?
Also Debug Log level does not give and additional information

**Comment by ValleBL** [comment]
Issue found: Blocked URL!

For me it was "unagi-na.amazon.com"
So look at your Web Filtering. Might have some block which are required
